version: "3"

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge

services:
  db_media:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:${POSTRGRES_DATA}
    networks:
      - my-network
    ports:
      - "5432:5432"

  media_service:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - db_psql
    networks:
      - my-network
